PASCUA_LabActivity/PASCUA_LabActivity/Controllers/InstructorController.cs
using Microsoft.AspNetCore.Mvc;
using PASCUA_LabActivity.Database;
using PASCUA_LabActivity.Models;

using PASCUA_LabActivity.Services;
namespace PASCUA_LabActivity.Controllers
{
    public class InstructorController : Controller
    {
            private readonly AppDbContext _dbContext;
            public InstructorController(AppDbContext dbContext)
            {
                _dbContext = dbContext;
            }

            public IActionResult Index()
        {

            return View(_dbContext.Instructor);
        }
        //public IActionResult Index()
        //{
            
        //    return View(_fakeData.InstructorList);
        //}
        [HttpGet]
        public IActionResult AddInstructor()
        {

            return View();
        }
        [HttpPost]
        public IActionResult AddInstructor(Instructor newInstructor)
        {
            //Instructor Instructor = new Instructor();
            _dbContext.Instructor.Add(newInstructor);
            return View("Index",  _dbContext.Instructor);
        }
        //=== EDIT 
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Instructor? Instructor = _dbContext.Instructor.FirstOrDefault(st => st.Id == id);

            if (Instructor != null) // verify if the Instructor exist
                return View(Instructor);

            return NotFound();
        }
        [HttpPost]
        public IActionResult Edit(Instructor InstructorChange)
        {
            Instructor? Instructor =  _dbContext.Instructor.FirstOrDefault(st => st.Id == InstructorChange.Id);
            if (Instructor != null)
            {
                Instructor.Id = InstructorChange.Id;
                Instructor.FirstName = InstructorChange.FirstName;
                Instructor.LastName = InstructorChange.LastName;
                Instructor.IsTenured = InstructorChange.IsTenured;
                Instructor.Rank = InstructorChange.Rank;
                Instructor.HiringDate = InstructorChange.HiringDate;

            }
            return View("Index",  _dbContext.Instructor);
        }


        //==================================
        public IActionResult ShowDetail(int id)
        {
            //hehe
            //Search for the Instructor whose id matches the given id
            Instructor? Instructor =  _dbContext.Instructor.FirstOrDefault(st => st.Id == id);
            
            if (Instructor != null)//was an Instructor found?
                return View(Instructor);

            return NotFound();
        }
        //================================
        [HttpGet]
        public IActionResult DeleteInstructor(int id)
        {
            Instructor? instructor =  _dbContext.Instructor.FirstOrDefault(st => st.Id == id);
             _dbContext.Instructor.Remove(instructor);
            if (instructor != null)//was an instructor found?
                return RedirectToAction("Index",  _dbContext.Instructor);

            return NotFound();
        }
    }
}

PASCUA_LabActivity/PASCUA_LabActivity/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using PASCUA_LabActivity.Database;
using PASCUA_LabActivity.Models;
using PASCUA_LabActivity.Services;

namespace PASCUA_LabActivity.Controllers
{
    public class StudentController : Controller
    {

        private readonly AppDbContext _dbContext;
        public StudentController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            
            return View(_dbContext.Student);
        }

        [HttpGet]
        public IActionResult AddStudent()
        {

            return View();
        }
        [HttpPost]
        public IActionResult AddStudent(Student newStudent)
        {
            //Student student = new Student();
            _dbContext.Student.Add(newStudent);
            return RedirectToAction("Index", _dbContext.Student);
        }
        //=== EDIT 
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Student? student = _dbContext.Student.FirstOrDefault(st=>st.Id == id);

            if(student !=null) // verify if the student exist
            return View(student);

            return NotFound();
        }
        [HttpPost]
        public IActionResult Edit(Student studentChange)
        {
            Student? student = _dbContext.Student.FirstOrDefault(st => st.Id == studentChange.Id);
            if(student != null)
            {
                student.Id = studentChange.Id;
                student.FirstName = studentChange.FirstName;
                student.LastName=studentChange.LastName;
                student.Course = studentChange.Course;
                student.AdmissionDate = studentChange.AdmissionDate;    
                student.Email = studentChange.Email;

            }
            return RedirectToAction("Index", _dbContext.Student);
        }


        //==================================

        public IActionResult ShowDetail(int id)
        {
            //Search for the student whose id matches the given id
            Student? student = _dbContext.Student.FirstOrDefault(st => st.Id == id);
            
            if (student != null)//was an student found?
                return View(student);

            return NotFound();
        }

        //==================================
        [HttpGet]
        public IActionResult DeleteStudent(int id)
        {
            Student? student = _dbContext.Student.FirstOrDefault(st => st.Id == id);
            _dbContext.Student.Remove(student);
            if (student != null)//was an student found?
                return RedirectToAction("Index", _dbContext.Student);

            return NotFound();
        }

    }
}

PASCUA_LabActivity/PASCUA_LabActivity/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PASCUA_LabActivity</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PASCUA_LabActivity.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PASCUA_LabActivity</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Student</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Instructor" asp-action="Index">Instr----</a>
                        </li>      
               
                                @if (User.Identity.IsAuthenticated)
                                {
                                    <li class="nav-item">
                                        <a class="nav-link " asp-area="" asp-action="Logout" asp-controller="Account">Logout</a>
                                    </li>
                                }
                                else
                                {
                                    <li class="nav-item">
                                        <a class="nav-link " asp-area="" asp-action="Login" asp-controller="Account">Login</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link " asp-area="" asp-action="RegisterView" asp-controller="Account">Register new Account</a>
                                    </li>
                                }
                    
                   

                    </ul>
                </div>
            </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PASCUA_LabActivity - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>